### PR TITLE
Design guideline updates

### PR DESCRIPTION
**Pull request by skistz**
Updated links to components, fixed typos.

### CODE REVIEW

**Comment by talimarcus** [comment]
I am reviewing this

**Comment by talimarcus** [comment]
I don't have write access to this repo, so sorry for the weird code review @skistz:

**pages/guidelines/materiality.html**
"The Design System color palette contains an extensive palette of greys designed to be used a material breaks on a page layout." --> do you mean "**as** material breaks" ?

**pages/guidelines/navigation.html**
"Px-app-nav is the core navigation component and offers several configuration to suit a variety of use cases." --> "offers several **configurations**" (plural)

"It can be configured horizontally, vertically or as a drop down menu." --> "drop down" should be "dropdown" (one word)

"Px-breadcrumbs provides the ability to show the user their path through you application and easily navigate up to a parent level." --> "...through **your** application..."

"Finally, px-branding-bar provides a location into apply some custom branding elements such as an application name, logo or specific color" --> I think you mean "...provides a location **to** apply..." (rather than "into"). But "location" feels weird here, maybe "space" or "place" ?

"The px-tabs component provides the functionality." --> "**this** functionality"


**pages/guidelines/page-layout.html**
"Layout items can be autosized, or given a specific width..." --> remove comma after "autosized"

"The flexbox module a wrapper around all of CSS flexbox's non-unit-based properties" --> "The flexbox module **is** a wrapper"

**Comment by talimarcus** [comment]
Looks good to me. Can you please merge this @mdwragg ?

**Comment by mdwragg** [comment]
On it.

**Comment by mdwragg** [comment]
Done. 💯 🐐

**Pull request merged**
